//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `MediaCellId`.
    static let mediaCellId: Rswift.ReuseIdentifier<MediaCollectionViewCell> = Rswift.ReuseIdentifier(identifier: "MediaCellId")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 0 localization keys.
    struct localizable {
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = IGLoginViewController
      
      let bundle = R.hostingBundle
      let igLoginVC = StoryboardViewControllerResource<IGLoginViewController>(identifier: "IGLoginVC")
      let igNavController = StoryboardViewControllerResource<UIKit.UINavigationController>(identifier: "IGNavController")
      let mediaGalleryVC = StoryboardViewControllerResource<MediaGalleryCollectionViewController>(identifier: "MediaGalleryVC")
      let name = "Main"
      
      func igLoginVC(_: Void = ()) -> IGLoginViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: igLoginVC)
      }
      
      func igNavController(_: Void = ()) -> UIKit.UINavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: igNavController)
      }
      
      func mediaGalleryVC(_: Void = ()) -> MediaGalleryCollectionViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: mediaGalleryVC)
      }
      
      static func validate() throws {
        if _R.storyboard.main().igLoginVC() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'igLoginVC' could not be loaded from storyboard 'Main' as 'IGLoginViewController'.") }
        if _R.storyboard.main().igNavController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'igNavController' could not be loaded from storyboard 'Main' as 'UIKit.UINavigationController'.") }
        if _R.storyboard.main().mediaGalleryVC() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'mediaGalleryVC' could not be loaded from storyboard 'Main' as 'MediaGalleryCollectionViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
